src/routes/routes.py
from flask import Blueprint, render_template, request
from src.services import filter as f, threading as thr
from src.database import DBManager


main = Blueprint('main_blueprint', __name__)


@main.route('index')
def index():
    news_list = thr.get_news()
    containers_list = thr.get_containers()
    thr.init_news.join()
    data = {
        'imgs': [new.get_image() for new in news_list],
        'titles': [str(new.get_title()) for new in news_list],
        'urls': [new.get_url() for new in news_list],
        'dates': [new.get_date() for new in news_list],
        'categories': [new.get_category() for new in news_list]
    }

    return render_template('indexFunc.html', data=data, containers=containers_list)


# Método para ver un contenedor específico
@main.route('ver_contenedor/<int:idn>')
def expand_container(idn):
    container = thr.get_containers().get(idn)
    return render_template('containerNews.html', container=container)


@main.route('/')
def start():
    thr.init_thread()
    return render_template('login.html')


# CAMBIAR LA RUTA
@main.route('login_users', methods=['POST'])
def login_users():
    if DBManager.login(request.form['username'], request.form['password']):
        return index()
    else:
        return render_template('fail_login.html')


@main.route('register.html')
def register_funct():
    return render_template('register.html')


@main.route('login_back')
def go_to_login():
    return render_template('login.html')


@main.route('login_back')
def go_to_profile():
    return render_template('perfil.html')


@main.route('termsandConditions')
def terms_conditions():
    return render_template('termsConditions.html')


@main.route('categories')
def go_to_categories():
    return render_template('categories.html')


@main.route('save_keyword', methods=['POST'])
def save_keyword():
    keyword = request.form['search']
    news_list = thr.get_news()
    filted_news = f.filter_by_words(keyword, news_list)
    data = {
        'imgs': [new.get_image() for new in filted_news],
        'titles': [new.get_title() for new in filted_news],
        'urls': [new.get_url() for new in filted_news],
        'keyword': keyword,
        'dates': [new.get_date() for new in filted_news],
        'categories': [new.get_category() for new in filted_news]
    }
    return render_template('categoriesFunc.html', data=data)


# @main.route('pruebaArticulos')
# def prueba_articulos():
#     global news
#     # news = ws.get_news()
#     data = {
#         'imgs' : [new.get_image() for new in news],
#         'titles' : [new.get_title() for new in news],
#         'urls' : [new.get_url() for new in news]
#     }
#     return render_template('pruebaArticulos.html', data=data)

# Aun en PROCESO se MEJORA y DEPURACIÓN

@main.route('save_commonuser', methods=['POST'])
def register_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


@main.route('save_companyUser', methods=['POST'])
def register_company_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


@main.route('save_journalistUser', methods=['POST'])
def register_journalist_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


# Métodos para el ADMINISTRADOR
@main.route('userAdmin.html')
def index_admin():
    # noticias = ws.get_news()
    # gr.graph_news_per_source(noticias)
    return render_template('userAdmin/indexAdmin.html')


@main.route('verifyUsers')
def verify_users():
    unchecked_users = DBManager.load_unchecked_users()
    return render_template('userAdmin/verifyUsers.html', unchecked_users=unchecked_users)


# Método para verificar a los usuarios (Y: cambiar el estado de is_checked a 'Y')
@main.route('process_verification', methods=['POST'])
def process_verification():
    user_id = request.form.get('user_id')
    action = request.form.get('action')  # 'accept' or 'reject'
    if action == 'accept':
        DBManager.update_user_checked(user_id)
    return render_template('userAdmin/verifyUsers.html')


@main.route('charts')
def charts():
    return render_template('userAdmin/charts.html')


@main.route('comments')
def comments():
    return render_template('userAdmin/comments.html')


@main.route('editUsers')
def edit_users():
    return render_template('userAdmin/editUsers.html')


@main.route('profileAdmin')
def profile_admin():
    return render_template('userAdmin/profileAdmin.html')


@main.route('pdfreader')
def pdf_reader():
    return render_template('userAdmin/pdfReader.html')

src/templates/categories.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="../static/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small"> <span id="currentDate"></span></a>
                        </li>

                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Contacto</a> <!-- LINK!!!-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="{{ url_for('main_blueprint.go_to_login') }}">Login</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <img src="../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="index.html">
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
            <a href="index.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span
                        class="text-white font-weight-normal">paper</span></h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{{ url_for('main_blueprint.index') }}" class="nav-item nav-link">Inicio</a>
                    <a href="{{ url_for('main_blueprint.go_to_categories') }}" class="nav-item nav-link">Noticias Guardadas</a>
                    <!--Add more items on the menu-->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown active">Categorías</a>
                        {% block categories %} {% endblock %}
                    </div>
                </div>


                <!-- search by keywords -->
                <form action="/save_keyword" method="post">
                    <div class="input-group ml-auto d-none d-lg-flex" style="max-width: 300px;">
                        <input type="text" class="form-control border-0" name="search" placeholder="Buscar">
                        <div class="input-group-append">
                            <button class="input-group-text bg-primary text-dark border-0 px-3">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Icon to enter in login-->
                <div class="login-icon">
                    <a href="login.html" class="nav-item nav-link">
                        <i class="fas fa-user"></i>
                    </a>

                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- Featured News Slider Start -->
    <div class="container-fluid pt-5 mb-3">
        <div class="container">
            <div class="section-title">
                <h4 class="m-0 text-uppercase font-weight-bold">Búsqueda "{{keyword}}"</h4>
            </div>
            <!--noticias -->
            <div class="owl-carousel news-carousel carousel-item-4 position-relative">
                {% block noticia_primera %} {% endblock %}
            </div>
        </div>
    </div>
    <!-- Featured News Slider End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-square back-to-top"><i class="fa fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="../static/js/main.js"></script>
    <script src="../static/js/date.js"></script>

</body>

</html>

src/templates/containerNewsFunc.html
{% extends 'containerNews.html' %}

{% block container_news %}


{% endblock%}

src/templates/fail_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../static/css/style.css" rel="stylesheet">

    <style>
       .container-lg {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 70%;
            max-width: 400px; /* Adjust the maximum width according to your preferences  */
            text-align: left; /* Centers the content inside the container */
        }

        form label {
            display: block;
            text-align: left;
            margin-bottom: 5px; /* Space between labels and input fields */
        }

        form input[type="submit"] {
            width: auto; /* Set the width according to the content */
            margin-bottom: 10px;
        }


        form input {
            width: 80%;
            padding: 8px;
            margin-bottom: 10px;
        }
    </style>

    <script src="../static/js/date.js"></script>
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#"><span id="currentDate"></span></a>
                        </li>
                        
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Contacto</a> <!-- LINK!!!-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="{{ url_for('main_blueprint.go_to_login') }}">Login </a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <a href="index.html" class="navbar-brand p-0 d-none d-lg-block">
                    <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span class="text-secondary font-weight-normal">paper</span></h1>
                </a>
            </div>
            
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Login Feedback -->
    <div class="container-lg">
        <br>
            <h2>Los datos son incorrectos</h2>
            <p> <a href="{{ url_for('main_blueprint.go_to_login') }}">Intentar de nuevo</a></p>
    </div>

    <script src="../static/js/date.js"></script>    
</body>

src/templates/fail_register_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../static/css/style.css" rel="stylesheet">

    <style>
       .container-lg {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 70%;
            max-width: 400px; /* Adjust the maximum width according to your preferences  */
            text-align: left; /* Centers the content inside the container */
        }

        form label {
            display: block;
            text-align: left;
            margin-bottom: 5px; /* Space between labels and input fields */
        }

        form input[type="submit"] {
            width: auto; /* Set the width according to the content */
            margin-bottom: 10px;
        }


        form input {
            width: 80%;
            padding: 8px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#"><span id="currentDate"></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="{{ url_for('main_blueprint.go_to_login') }}">Login</a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <a href={{ url_for('index') }}" class="navbar-brand p-0 d-none d-lg-block">
                    <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span class="text-secondary font-weight-normal">paper</span></h1>
                </a>
            </div>
            
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Login Feedback -->
    <div class="container-lg">
        <br>
            <h2>Email no válido</h2>
            <p><a href="{{ url_for('main_blueprint.go_to_login') }}"> Intenténtalo de nuevo</a></p>
    </div>

    <script src="../static/js/date.js"></script>    
</body>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../static/img/logos/high_res/logo_color_tbg_hd.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../static/css/style.css" rel="stylesheet">

    <!--Other Bootstrap Libraries for the dropdown menu-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.9/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Date and Main Scripts-->
    <script src="../static/js/date.js"></script>
    <script src="../static/js/main.js"></script>

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small"> <span id="currentDate"></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="{{ url_for('main_blueprint.go_to_login') }}">Login</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <img src="../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="index.html">
            </div>

            <!-- Example of an advertisement
        <div class="col-lg-8 text-center text-lg-right">
            <a href="https://htmlcodex.com"><img class="img-fluid" src="img/ads-728x90.png" alt=""></a>
        </div>
        -->

        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
            <a href= "{{ url_for('main_blueprint.index') }}"  class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span
                        class="text-white font-weight-normal">paper</span></h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{{ url_for('main_blueprint.index') }}" class="nav-item nav-link active">Inicio</a>
                    <a href="{{ url_for('main_blueprint.go_to_categories') }}" class="nav-item nav-link">Noticias Guardadas</a>
                    <!--Add more items on the menu-->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Categorías</a>
                            <a href="#" class="dropdown-item">Economía</a>
                            <a href="#" class="dropdown-item">Tecnología</a>
                            <a href="#" class="dropdown-item">Salud</a>
                        </div>
                    </div>
                </div>


                <!-- search by keywords -->
                <form action="/save_keyword" method="post">
                    <div class="input-group ml-auto d-none d-lg-flex" style="max-width: 300px;">
                        <input type="text" class="form-control border-0" name="search" placeholder="Buscar">
                        <div class="input-group-append">
                            <button class="input-group-text bg-primary text-dark border-0 px-3">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Icon to enter in login-->
                <div class="login-icon">
                    <a href= "{{ url_for('main_blueprint.go_to_profile') }}" class="nav-item nav-link">
                        <i class="fas fa-user"></i>
                    </a>

                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- Main News Slider Start -->
    <div class="container-fluid" style="width: 100%;">
        <div class="row justify-content-md-center">
            <div class="col-lg-7 px-0">
                <!--Big slide-->
                <!-- Trending topic or breaking news,...-->
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner absolute">
                        <!--inicio primera noticia (La grande)-->
                        {% block primera_noticia %}{% endblock %}
                         <!--fin primera noticia-->
                        {% block segunda_noticia %}{% endblock %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>


            </div>
            <div class="col-lg-5 px-0">
                <div class="row mx-0">
                    <!-- Mini Slides-->
                    {% block mini_slide %} {% endblock %}
                    <!--End mini Slides-->
                </div>
            </div>
        </div>
    </div>
    <!-- Main News Slider End -->

    <br>

    <!-- News With Sidebar Start -->
    <div class="container-fluid" style="width: 100%; height: 100%;">
        <div >
            <div class="row justify-content-md-center">
                <!-- Tranding News Start -->
                <div class="col-md-11">
                    <div>
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Noticias recomendadas</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            {% block recommended_news %} {% endblock%}   
                        </div>
                    </div>
                </div>
                <!-- Tranding News End -->
            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->
</body>

src/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../static/css/style.css" rel="stylesheet">

    <style>
       .container-lg {
            position: absolute;
            margin-top: 5%;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 70%;
            max-width: 400px; /* Adjust the maximum width according to your preferences  */
            text-align: left; /* Centers the content inside the container */
        }

        form label {
            display: block;
            text-align: left;
            margin-bottom: 5px; /* Space between labels and input fields */
        }

        form input[type="submit"] {
            width: auto; /* Set the width according to the content */
            margin-bottom: 10px;
        }


        form input {
            width: 80%;
            padding: 8px;
            margin-bottom: 10px;
        }
    </style>

    <script src="../static/js/date.js"></script>
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#"><span id="currentDate"></span></a>
                        </li>
                        
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Contacto</a> <!-- LINK!!!-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="{{ url_for('main_blueprint.go_to_login') }}">Login</a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <img src="../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="register.html">
            </div>
            
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Login -->
    <div class="container-lg">
        <br>
        <h2>Iniciar Sesión</h2>
        <form action="/login_users" method="post"> 
            <label for="username">Usuario o email:</label>
            <input type="text" id="username" name="username" required><br>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required><br>
            <label for="terms">Acepta los <a href="{{ url_for('main_blueprint.terms_conditions') }}"> Términos y condiciones: </a></label>
            <input type="checkbox" name="terms" value="terms" style=" float: right; margin-left: 30px;" required><br>
            <input type="submit" value="Iniciar Sesión"> 
        </form>
        <p>¿Nuevo aquí? <a href="register.html">Regístrate</a></p>
        <p><a href="forgotten_passwd.html">¿Olvidaste tu contraseña?</a></p>
        
        <!-- BOTÓN PARA QUE ME LLEVE AL ADMIN Y PODER TRABAJAR >>> BORRAR EN EL FUTURO -->
        <a href="{{ url_for('main_blueprint.index_admin') }}">Usuario Administrador</a>
    </div>

    <script src="../static/js/date.js"></script>    
</body>