src/routes/routes.py
from flask import Blueprint, render_template, request
from src.services import filter as f, threading as thr
from src.database import DBManager


main = Blueprint('main_blueprint', __name__)


@main.route('index')
def index():
    news_list = thr.get_news()
    containers_list = thr.get_containers()
    thr.init_news.join()
    data = {
        'imgs': [new.get_image() for new in news_list],
        'titles': [str(new.get_title()) for new in news_list],
        'urls': [new.get_url() for new in news_list],
        'dates': [new.get_date() for new in news_list],
        'categories': [new.get_category() for new in news_list]
    }

    return render_template('indexFunc.html', data=data, containers=containers_list)


# Método para ver un contenedor específico
@main.route('ver_contenedor/<int:idn>')
def expand_container(idn):
    container = thr.get_containers().get(idn)
    return render_template('containerNews.html', container=container)


@main.route('/')
def start():
    thr.init_thread()
    return render_template('login.html')


# CAMBIAR LA RUTA
@main.route('login_users', methods=['POST'])
def login_users():
    if DBManager.login(request.form['username'], request.form['password']):
        return index()
    else:
        return render_template('fail_login.html')


@main.route('register.html')
def register_funct():
    return render_template('register.html')


@main.route('login_back')
def go_to_login():
    return render_template('login.html')


@main.route('login_back')
def go_to_profile():
    return render_template('perfil.html')


@main.route('termsandConditions')
def terms_conditions():
    return render_template('termsConditions.html')


@main.route('categories')
def go_to_categories():
    return render_template('categories.html')


@main.route('save_keyword', methods=['POST'])
def save_keyword():
    keyword = request.form['search']
    news_list = thr.get_news()
    filted_news = f.filter_by_words(keyword, news_list)
    data = {
        'imgs': [new.get_image() for new in filted_news],
        'titles': [new.get_title() for new in filted_news],
        'urls': [new.get_url() for new in filted_news],
        'keyword': keyword,
        'dates': [new.get_date() for new in filted_news],
        'categories': [new.get_category() for new in filted_news]
    }
    return render_template('categoriesFunc.html', data=data)


# @main.route('pruebaArticulos')
# def prueba_articulos():
#     global news
#     # news = ws.get_news()
#     data = {
#         'imgs' : [new.get_image() for new in news],
#         'titles' : [new.get_title() for new in news],
#         'urls' : [new.get_url() for new in news]
#     }
#     return render_template('pruebaArticulos.html', data=data)

# Aun en PROCESO se MEJORA y DEPURACIÓN

@main.route('save_commonuser', methods=['POST'])
def register_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


@main.route('save_companyUser', methods=['POST'])
def register_company_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


@main.route('save_journalistUser', methods=['POST'])
def register_journalist_user():
    result = DBManager.save_user()
    if result == -1:
        return render_template('fail_register_password.html')
    elif result == -2:
        return render_template('fail_register_email.html')
    else:
        if DBManager.save_journalist_user(result):
            return index()


# Métodos para el ADMINISTRADOR
@main.route('userAdmin.html')
def index_admin():
    # noticias = ws.get_news()
    # gr.graph_news_per_source(noticias)
    return render_template('userAdmin/indexAdmin.html')


@main.route('verifyUsers')
def verify_users():
    unchecked_users = DBManager.load_unchecked_users()
    return render_template('userAdmin/verifyUsers.html', unchecked_users=unchecked_users)


# Método para verificar a los usuarios (Y: cambiar el estado de is_checked a 'Y')
@main.route('process_verification', methods=['POST'])
def process_verification():
    user_id = request.form.get('user_id')
    action = request.form.get('action')  # 'accept' or 'reject'
    if action == 'accept':
        DBManager.update_user_checked(user_id)
    return render_template('userAdmin/verifyUsers.html')


@main.route('charts')
def charts():
    return render_template('userAdmin/charts.html')


@main.route('comments')
def comments():
    return render_template('userAdmin/comments.html')


@main.route('editUsers')
def edit_users():
    return render_template('userAdmin/editUsers.html')


@main.route('profileAdmin')
def profile_admin():
    return render_template('userAdmin/profileAdmin.html')


@main.route('pdfreader')
def pdf_reader():
    return render_template('userAdmin/pdfReader.html')

src/templates/userAdmin/charts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper Administrador</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../../static/css/style.css" rel="stylesheet">

    <!--Other Bootstrap Libraries for the dropdown menu-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.9/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Date and Main Scripts-->
    <script src="../../static/js/date.js"></script>
    <script src="../../static/js/main.js"></script>

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small"> <span id="currentDate"></span></a>
                        </li>
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small">Administrador </a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <div class="col-lg-4">
                    <img src="../../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="indexAdmin.html">
                </div>
            </div>

        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
            <a href="indexAdmin.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span
                        class="text-white font-weight-normal">paper</span></h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{{ url_for('main_blueprint.index_admin') }}" class="nav-item nav-link">Inicio</a>
                    <a href="{{ url_for('main_blueprint.verify_users') }}" class="nav-item nav-link">Verificación</a>
                    <a href="{{ url_for('main_blueprint.charts') }}" class="nav-item nav-link">Gráficos</a>
                    <a href="{{ url_for('main_blueprint.comments') }}" class="nav-item nav-link">Comentarios</a>
                    <a href="{{ url_for('main_blueprint.edit_users') }}" class="nav-item nav-link active">Editar Usuarios</a>
                </div>

                <!-- Icon to enter in login-->
                <div class="login-icon">
                    <a href="{{ url_for('main_blueprint.profile_admin') }}" class="nav-item nav-link">
                        <i class="fas fa-user"></i>
                    </a>

                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- News With Sidebar Start -->
    <div class="container-fluid" style="margin-top: 5%;">
        <div >
            <div class="row justify-content-md-center">
                <!-- Gráficos-->
                <div class="col-md-11">
                    <div>
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Gráficos </h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Noticias por fuente: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Gráfico de noticias por fuente">
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Gráfico de visualizaciones de categorías: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Gráfico de visualizaciones de categorías">
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Visualizaciones: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Visualizaciones">
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Nube de palabras: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Nube de palabras">
                        </div>
                    </div>
                </div>
                <!--  Gráficos End -->

            </div>
        </div>
    </div>

</body>

src/templates/userAdmin/editUsers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper Administrador</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../../static/css/style.css" rel="stylesheet">

    <!--Other Bootstrap Libraries for the dropdown menu-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.9/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Date and Main Scripts-->
    <script src="../../static/js/date.js"></script>
    <script src="../../static/js/main.js"></script>


    <style>
       .section-title mb-0 {
            position: absolute;
            margin-top: 5%;
           margin-bottom: 30%;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 70%;
            max-width: 400px; /* Adjust the maximum width according to your preferences  */
            text-align: left; /* Centers the content inside the container */
        }

        form label {
            display: block;
            text-align: left;
            margin-bottom: 5px; /* Space between labels and input fields */
        }

        form input[type="submit"] {
            width: auto; /* Set the width according to the content */
            margin-bottom: 10px;
        }


        form input {
            width: 80%;
            padding: 8px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small"> <span id="currentDate"></span></a>
                        </li>
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small">Administrador </a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <div class="col-lg-4">
                    <img src="../../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="indexAdmin.html">
                </div>
            </div>

        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
            <a href="indexAdmin.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span
                        class="text-white font-weight-normal">paper</span></h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{{ url_for('main_blueprint.index_admin') }}" class="nav-item nav-link active">Inicio</a>
                    <a href="{{ url_for('main_blueprint.verify_users') }}" class="nav-item nav-link">Verificación</a>
                    <a href="{{ url_for('main_blueprint.charts') }}" class="nav-item nav-link">Gráficos</a>
                    <a href="{{ url_for('main_blueprint.comments') }}" class="nav-item nav-link">Comentarios</a>
                    <a href="{{ url_for('main_blueprint.edit_users') }}" class="nav-item nav-link">Editar Usuarios</a>
                </div>

                <!-- Icon to enter in login-->
                <div class="login-icon">
                    <a href="{{ url_for('main_blueprint.profile_admin') }}" class="nav-item nav-link">
                        <i class="fas fa-user"></i>
                    </a>

                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- News With Sidebar Start -->
    <div class="container-fluid" style="margin-top: 5%;">
        <div >
            <div class="row justify-content-md-center">
                <!-- Editar de Usuarios-->
                <div class="col-md-11">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Editar usuario</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <form action="/edit_user" method="post">
                                <label for="username">Nombre de Usuario:</label>
                                <input type="text" id="username" name="username" required><br>

                                <label for="password">Contraseña:</label>
                                <input type="password" id="password" name="password" required><br>

                                <label for="email">Email:</label>
                                <input type="email" id="email" name="email" required><br>

                                <input type="submit" value="Editar Usuario">
                            </form>
                        </div>
                    </div>
                <!--  Editar End -->
                <!-- Borrar de Usuarios-->
                <div class="col-md-11">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Borrar usuarios</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                        <form action="/delete-user" method="post">
                            <label for="username_delete">Username:</label>
                            <input type="text" id="username_delete" name="username_delete" required><br>

                            <input type="submit" value="Borrar Usuario">
                            </form>
                         </div>
                </div>
                <!--  Borrar End -->

                <!-- Crear de Usuarios-->
                <div class="col-md-11">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Crear usuarios</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <form action="/create_user" method="post">
                                <label for="username_new">Nombre de Usuario:</label>
                                <input type="text" id="username_new" name="username_new" required> <br>

                                <label for="password_new">Contraseña:</label>
                                <input type="password" id="password_new" name="password_new" required><br>

                                <label for="email_new">Email:</label>
                                <input type="email" id="email_new" name="email_new" required><br>

                                <input type="submit" value="Crear Usuario">
                            </form>
                        </div>
                </div>
                <!--  Crear End -->

            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->

</body>

src/templates/userAdmin/indexAdmin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TruthPaper Administrador</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Icon -->
    <link href="../../static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Bootstrap Stylesheet -->
    <link href="../../static/css/style.css" rel="stylesheet">

    <!--Other Bootstrap Libraries for the dropdown menu-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.9/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Date and Main Scripts-->
    <script src="../../static/js/date.js"></script>
    <script src="../../static/js/main.js"></script>

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small"> <span id="currentDate"></span></a>
                        </li>
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small">Administrador </a> <!-- LINK!!!-->
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <!-- We can put something in the upper right part of the black bar at the top of the screen -->>
            </div>
        </div>

        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <div class="col-lg-4">
                    <img src="../../static/img/logos/high_res/logo_color_tbg_hd.png" alt="" class="img-fluid" width="200" href="indexAdmin.html">
                </div>
            </div>

        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
            <a href="indexAdmin.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-uppercase text-primary">Truth<span
                        class="text-white font-weight-normal">paper</span></h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{{ url_for('main_blueprint.index_admin') }}" class="nav-item nav-link active">Inicio</a>
                    <a href="{{ url_for('main_blueprint.verify_users') }}" class="nav-item nav-link">Verificación</a>
                    <a href="{{ url_for('main_blueprint.charts') }}" class="nav-item nav-link">Gráficos</a>
                    <a href="{{ url_for('main_blueprint.comments') }}" class="nav-item nav-link">Comentarios</a>
                    <a href="{{ url_for('main_blueprint.edit_users') }}" class="nav-item nav-link">Editar Usuarios</a>
                </div>

                <!-- Icon to enter in login-->
                <div class="login-icon">
                    <a href="{{ url_for('main_blueprint.go_to_profile') }}" class="nav-item nav-link">
                        <i class="fas fa-user"></i>
                    </a>

                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- News With Sidebar Start -->
    <div class="container-fluid" style="margin-top: 5%;">
        <div >
            <div class="row justify-content-md-center">
                <!-- Verificación de Usuarios-->
                <div class="col-md-11">
                    <div>
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Verificación de usuarios</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            {% block verify_users %} {% endblock%}
                        </div>
                    </div>
                </div>
                <!--  Verificación End -->
                <!-- Gráficos-->
                <div class="col-md-11" style="margin-top: 5%;">
                    <div>
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Gráficos </h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Noticias por fuente: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Gráfico de noticias por fuente">
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Gráfico de visualizaciones de categorías: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Gráfico de visualizaciones de categorías">
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <h5> Nube de palabras: </h5>
                            <img src="../../static/img/graphs/news_per_source.png" alt="Nube de palabras">
                        </div>
                    </div>
                </div>
                <!--  Gráficos End -->

            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->

</body>

src/templates/userAdmin/indexAdminFunc.html
{% extends 'indexAdmin.html' %}


{% endblock%}

src/templates/userAdmin/verifyUsersFunc.html
{% extends 'verifyUsers.html' %}

<!--
{% block journalist_users  %}
    {% for user in journalist_users %}
    <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
        <div style=" height: 110px; width: 155px;">
        </div>
        
        <div
            class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0" style="height: 50px; width: auto;">
            <div class="mb-2">
                <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2"
                    href="">Periodista</a>
            </div>
            <a class="h6 m-0 text-secondary text-uppercase font-weight-bold">{{user.name}}</a>
            <p> Email del usuario: {{user.email}}</p>
             Este botón abre un lector de pdf
            <form action="pdfreader.html" method="post">
                <input type="hidden" name="pdf_url" value="{{journalist_user.pdf}}">
                <input type="submit" value="Abrir Certificado del periodista">
            </form>
            <form action="/verify_users" method="post">
                <input type="submit" value="Aceptar" class="btn btn-primary" style="width: 100px; color: green;">
                <input type="submit" value="Denegar" class="btn btn-primary" style="width: 100px; color: red;">
            </form>
             Si se pulsa aceptar/denegar >> enviar correo -
        </div>  
    </div>
    {% endfor %}

{% endblock %}
-->

{% block company_users  %}
    {% for user_dict in company_users %}
        {% for key, value in user_dict.items() %}
        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0" style="height: 50px; width: auto;">
                <div class="mb-2">
                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Empresa</a>
                </div>
                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold">{{ user.name }}</a>
                <p> NIF: {{ user.nif }}</p>
                <form action="/process_verification" method="post">
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="action" value="accept">
                    <input type="submit" value="Aceptar" class="btn btn-primary" style="width: 100px; color: green;">
                    <input type="submit" value="Denegar" class="btn btn-primary" style="width: 100px; color: red;">
                    <!-- el botón denegar no hace nada, pero se puede implementar en el futuro -->

                    <!-- Script que envia "deny" si es denegar y "accept" si es aceptar -->
                    <script>
                        function setAction(event) {
                            var acceptButton = document.querySelector('input[value="Aceptar"]');
                            var denyButton = document.querySelector('input[value="Denegar"]');
                            var actionInput = document.getElementById('action');

                            if (acceptButton && denyButton && actionInput) {
                                if (acceptButton.clicked) {
                                    actionInput.value = 'accept';
                                } else if (denyButton.clicked) {
                                    actionInput.value = 'deny';
                                }
                            }
                            return true;
                        }
                    </script>
                </form>
            </div>
        </div>
        {% endfor %}
    {% endfor %}

{% endblock %}